// <auto-generated />
using System;
using FBC.Basit.Cari.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBC.Basit.Cari.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20211226073949_user-fk-carikart")]
    partial class userfkcarikart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.CariHareket", b =>
                {
                    b.Property<int>("CariHareketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Alacak")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Borc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CariKartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvrakNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("CariHareketId");

                    b.HasIndex("CariKartId");

                    b.ToTable("CariHareket");
                });

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.CariKart", b =>
                {
                    b.Property<int>("CariKartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CariKartId");

                    b.ToTable("CariKart");
                });

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.SysUser", b =>
                {
                    b.Property<int>("SysUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CariKartId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanEditData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SysUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SysUserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SysUserId");

                    b.HasIndex("CariKartId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.CariHareket", b =>
                {
                    b.HasOne("FBC.Basit.Cari.DBModels.CariKart", "CariKart")
                        .WithMany("Hareketler")
                        .HasForeignKey("CariKartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.SysUser", b =>
                {
                    b.HasOne("FBC.Basit.Cari.DBModels.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId");

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("FBC.Basit.Cari.DBModels.CariKart", b =>
                {
                    b.Navigation("Hareketler");
                });
#pragma warning restore 612, 618
        }
    }
}
